# Generated by Django 3.2.5 on 2022-01-08 16:30

import asrot_server.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=500)),
                ('task_name', models.CharField(max_length=500)),
                ('audio_filename', models.CharField(max_length=1000)),
                ('data_path', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(default=asrot_server.models.get_default_my_date)),
                ('language', models.CharField(max_length=500)),
                ('transcription_hypo', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_correct', models.CharField(max_length=1000)),
                ('first_commit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_commit', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asrot_server.transcriptiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
