# Generated by Django 3.2.5 on 2022-01-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asrot_server', '0002_auto_20220108_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptioncorrection',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asrot_server.transcriptiontask'),
        ),
    ]
