# Generated by Django 3.2.5 on 2022-01-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asrot_server', '0003_alter_transcriptioncorrection_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiontask',
            name='file_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcriptioncorrection',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asrot_server.transcriptiontask'),
        ),
    ]
